name: secret_santa
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  intl: ^0.20.1
  flutter_layout_grid: ^2.0.7
  flutter_rating_bar: 4.0.1
  go_router: ^14.6.2
  # flutter_sms: ^2.3.3
  flash_card: ^0.1.0
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  build_runner: ^2.4.8
  # the code generator
  riverpod_generator: ^2.4.0
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.3.10
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.7.0

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
